# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=10)),
                ('s_tel', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'day5_stu',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_addr', models.CharField(max_length=30)),
                ('i_image', models.ImageField(null=True, upload_to='upload')),
                ('s', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stu.Student')),
            ],
            options={
                'db_table': 'day5_stuinfo',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_url', models.CharField(max_length=30)),
                ('v_time', models.IntegerField()),
            ],
            options={
                'db_table': 'visit',
            },
        ),
    ]
